export enum EActivityType {
  LOGIN = 'login',
  LOGOUT = 'logout',
  JOINED_CLASS = 'joined_class',
  ENTERED_CLASS = 'entered_class',
  EXITED_CLASS = 'exited_class',
  STARTED_LESSON = 'started_lesson',
  PAUSED_LESSON = 'paused_lesson',
  STOPPED_LESSON = 'stopped_lesson',
  COMPLETED_LESSON = 'completed_lesson',
  STARTED_QUIZ = 'started_quiz',
  PAUSED_QUIZ = 'paused_quiz',
  STOPPED_QUIZ = 'stopped_quiz',
  COMPLETED_QUIZ = 'completed_quiz',
  CLICKED_LINK = 'clicked_link',
}
